indexing-settings:
  sites:
    - url: http://playback.ru/
      name: playback

    - url: https://volochek.life/
      name: volochek

    - url: https://ipfran.ru/
      name: ipfran

  name: SearchBotFix/2.0
  referer: https://google.com
  timeout: 15000
  contentType: text/html; charset=utf-8

search-settings:
  limit: 20
  offset: 0